# generated by datamodel-codegen:
#   filename:  config-schema.json
#   timestamp: 2026-02-14T11:17:51+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AnyUrl, BaseModel, Field


class Mode(Enum):
    single = 'single'
    multi = 'multi'


class Project(BaseModel):
    name: str | None = Field(None, description='Project name shown in the web export')
    uri: AnyUrl | None = Field(
        None, description='Project URI (link in the web interface)'
    )
    export_filename_prefix: str | None = Field(
        None, alias='export-filename-prefix', description='Prefix for downloaded files'
    )
    mode: Mode | None = Field(
        'single',
        description='Output mode: single (one model) or multi (multiple models with index)',
    )
    head_extra: str | None = Field(
        '', alias='head-extra', description='HTML injected at end of <head> tag'
    )


class FontSource(Enum):
    auto = 'auto'
    appimage = 'appimage'
    system = 'system'


class Openscad(BaseModel):
    version: str | None = Field(
        '2026.01.19',
        description='OpenSCAD version to download',
        pattern='^\\d{4}\\.\\d{2}\\.\\d{2}$',
    )
    sha256_appimage: str | None = Field(
        None,
        alias='sha256-appimage',
        description='SHA256 checksum of the OpenSCAD AppImage to download',
        pattern='^[0-9a-fA-F]{64}$',
    )
    sha256_wasm_web: str | None = Field(
        None,
        alias='sha256-wasm-web',
        description='SHA256 checksum of the OpenSCAD WASM web zip to download',
        pattern='^[0-9a-fA-F]{64}$',
    )
    font_source: FontSource | None = Field(
        'auto', alias='font-source', description='Font source selection'
    )


class ModelItem(BaseModel):
    file: str = Field(..., description='Path to SCAD file')
    additional_params: list[str] | None = Field(
        [], alias='additional-params', description='Array of parameter JSON files'
    )
    description_extra_html: str | None = Field(
        None, alias='description-extra-html', description='Per-file HTML description'
    )


class WebOpenscadEditorConfiguration(BaseModel):
    project: Project | None = Field(
        None, description='Project metadata displayed in the web interface'
    )
    openscad: Openscad | None = Field(
        default_factory=lambda: Openscad.model_validate({}),
        description='OpenSCAD-specific configuration',
    )
    model: list[ModelItem] = Field(
        ..., description='Input SCAD files to process', min_length=1
    )
